import type { WordEntry } from "./words";

/**
 * Bonus built-in banks beyond the four grade bands. Same data rules as
 * lib/words.ts: sentence uses the word exactly once, hint never contains it.
 */

export const SIGHT_WORDS: WordEntry[] = [
  { word: "the", hint: "It comes before almost every noun — you'll see it everywhere!", sentence: "Look at the enormous pumpkin!" },
  { word: "and", hint: "It glues two things together, like peanut butter with jelly.", sentence: "We bought apples and bananas." },
  { word: "said", hint: "The past of say.", sentence: "Mom said dinner is ready." },
  { word: "come", hint: "The opposite of go.", sentence: "Please come to my party!" },
  { word: "here", hint: "This very spot — not over there.", sentence: "Your seat is right here." },
  { word: "look", hint: "What your eyes do on purpose.", sentence: "Come look at this rainbow!" },
  { word: "play", hint: "What you do at recess.", sentence: "Let's play tag outside." },
  { word: "was", hint: "The past of is.", sentence: "Yesterday was my birthday." },
  { word: "you", hint: "The person I'm talking to!", sentence: "Do you like puzzles?" },
  { word: "are", hint: "We ___ best friends.", sentence: "Where are my shoes?" },
  { word: "they", hint: "Those people over there.", sentence: "Are they coming to lunch?" },
  { word: "what", hint: "The question word for things.", sentence: "Guess what I found today!" },
  { word: "have", hint: "To own it or hold it.", sentence: "I have two goldfish." },
  { word: "want", hint: "To wish for something.", sentence: "I want to learn to skate." },
  { word: "went", hint: "The past of go.", sentence: "We went to the fair on Saturday." },
  { word: "this", hint: "The one right in front of you.", sentence: "Is this seat taken?" },
  { word: "that", hint: "The one farther away from you.", sentence: "Whose backpack is that?" },
  { word: "with", hint: "Together — not alone.", sentence: "Walk with me to class." },
  { word: "from", hint: "Where something started out.", sentence: "This letter is from Grandpa." },
  { word: "your", hint: "Belonging to the person I'm talking to.", sentence: "Is this your jacket?" },
  { word: "some", hint: "A few, but not all.", sentence: "Would you like some grapes?" },
  { word: "when", hint: "The question word for time.", sentence: "Ask when the show starts." },
  { word: "will", hint: "It ___ rain tomorrow.", sentence: "We will visit the zoo soon." },
  { word: "like", hint: "To enjoy something a lot.", sentence: "Puppies like belly rubs." },
  { word: "then", hint: "Right after that.", sentence: "We ate lunch, then played outside." },
  { word: "them", hint: "Those people — give it to ___.", sentence: "Hand them the crayons, please." },
  { word: "our", hint: "Belonging to us.", sentence: "This is our classroom." },
  { word: "out", hint: "The opposite of in.", sentence: "The cat wants out of the house." },
  { word: "who", hint: "The question word for people.", sentence: "Guess who won the raffle!" },
  { word: "how", hint: "The question word for the way things work.", sentence: "Show me how to fold a crane." },
  { word: "now", hint: "This very moment.", sentence: "The bus is leaving right now." },
  { word: "down", hint: "The opposite of up.", sentence: "The ball rolled down the hill." },
  { word: "very", hint: "Extra! Really! So much!", sentence: "The soup is very hot." },
  { word: "make", hint: "To build or create something.", sentence: "Let's make paper airplanes." },
  { word: "into", hint: "From outside to inside.", sentence: "The frog hopped into the pond." },
  { word: "good", hint: "The opposite of bad.", sentence: "That was a good catch!" },
  { word: "see", hint: "What your eyes let you do.", sentence: "Can you see the lighthouse?" },
  { word: "two", hint: "The number between one and three.", sentence: "I have two little sisters." },
  { word: "one", hint: "The very first counting number.", sentence: "Only one cookie is left." },
  { word: "because", hint: "The word that gives the reason.", sentence: "We hurried because rain was coming." },
];

export const COMMONLY_MISSPELLED: WordEntry[] = [
  { word: "accidentally", hint: "By mistake — you didn't mean to.", sentence: "I accidentally wore two different socks." },
  { word: "apparently", hint: "So it seems, from what people say.", sentence: "Apparently the game got moved to Friday." },
  { word: "basically", hint: "In the simplest way of putting it.", sentence: "The recipe is basically just three steps." },
  { word: "beginning", hint: "The very start.", sentence: "Start reading from the beginning." },
  { word: "believe", hint: "To think it's true.", sentence: "I believe you can do it." },
  { word: "business", hint: "A company that sells things or services.", sentence: "Her aunt runs a bakery business." },
  { word: "calendar", hint: "It shows the months and days.", sentence: "Circle the date on the calendar." },
  { word: "cemetery", hint: "A quiet field of gravestones.", sentence: "The cemetery gate creaked in the wind." },
  { word: "definitely", hint: "For sure — one hundred percent.", sentence: "We will definitely be there." },
  { word: "embarrass", hint: "To make someone's cheeks turn red.", sentence: "Don't embarrass me in front of everyone." },
  { word: "environment", hint: "The natural world all around us.", sentence: "Planting trees helps the environment." },
  { word: "existence", hint: "The state of being real.", sentence: "The map proved the island's existence." },
  { word: "familiar", hint: "Known to you already.", sentence: "Her voice sounded familiar on the phone." },
  { word: "finally", hint: "At last, after a long wait.", sentence: "The package finally arrived." },
  { word: "forty", hint: "The number after thirty-nine.", sentence: "The trip takes forty minutes." },
  { word: "friend", hint: "Someone you love to spend time with.", sentence: "A good friend shares the swing." },
  { word: "government", hint: "The group that runs a country or town.", sentence: "The government opened a new library." },
  { word: "grateful", hint: "Full of thanks.", sentence: "We're grateful for the warm meal." },
  { word: "happened", hint: "The past of happen.", sentence: "Nobody saw what happened backstage." },
  { word: "immediately", hint: "Right now, without waiting.", sentence: "The alarm rang and we left immediately." },
  { word: "independent", hint: "Able to do things on your own.", sentence: "The kitten is fiercely independent." },
  { word: "knowledge", hint: "Everything you know.", sentence: "The quiz tested our science knowledge." },
  { word: "necessary", hint: "Something you must have or do.", sentence: "Sunscreen is necessary at the beach." },
  { word: "neighbor", hint: "The person who lives next door.", sentence: "Our neighbor grows giant sunflowers." },
  { word: "receive", hint: "To get something given to you.", sentence: "Did you receive the invitation?" },
  { word: "rhythm", hint: "The beat you tap your foot to.", sentence: "Clap the rhythm with me." },
  { word: "separate", hint: "To split apart into groups.", sentence: "Please separate the markers by color." },
  { word: "truly", hint: "Honestly and really.", sentence: "I am truly sorry about your kite." },
  { word: "until", hint: "Up to that time.", sentence: "Stir until the sugar disappears." },
  { word: "weird", hint: "Strange and a little bit odd.", sentence: "That cloud has a weird shape." },
];

export const ANIMALS_NATURE: WordEntry[] = [
  { word: "butterfly", hint: "It starts as a caterpillar, then grows wings.", sentence: "A butterfly landed on the daisy." },
  { word: "caterpillar", hint: "The wiggly stage before the wings.", sentence: "The caterpillar munched every leaf." },
  { word: "dolphin", hint: "The clever gray swimmer that clicks and whistles.", sentence: "A dolphin leaped beside the boat." },
  { word: "eagle", hint: "The huge bird with amazing eyesight.", sentence: "An eagle circled high above the lake." },
  { word: "elephant", hint: "The biggest land animal, with a trunk.", sentence: "The elephant sprayed water everywhere." },
  { word: "flamingo", hint: "The pink bird that stands on one leg.", sentence: "The flamingo napped standing up." },
  { word: "forest", hint: "A huge area full of trees.", sentence: "Deer live deep in the forest." },
  { word: "giraffe", hint: "The tallest animal, with a very long neck.", sentence: "The giraffe nibbled the treetops." },
  { word: "hedgehog", hint: "A tiny animal covered in spines.", sentence: "The hedgehog rolled into a ball." },
  { word: "island", hint: "Land with water all the way around.", sentence: "Turtles nest on that sandy island." },
  { word: "jungle", hint: "A thick, steamy forest full of vines.", sentence: "Parrots squawked across the jungle." },
  { word: "kangaroo", hint: "It hops on big feet and carries babies in a pouch.", sentence: "The kangaroo bounded across the field." },
  { word: "koala", hint: "The sleepy climber that eats eucalyptus.", sentence: "The koala dozed in the branches." },
  { word: "leopard", hint: "The spotted big cat that climbs trees.", sentence: "A leopard rested on the branch." },
  { word: "meadow", hint: "A grassy field full of wildflowers.", sentence: "Bees hummed across the meadow." },
  { word: "mountain", hint: "A giant rocky peak.", sentence: "Snow covered the mountain all year." },
  { word: "octopus", hint: "Eight arms and a soft, clever body.", sentence: "The octopus squeezed into the jar." },
  { word: "penguin", hint: "The tuxedo bird that swims but can't fly.", sentence: "The penguin slid across the ice." },
  { word: "rainbow", hint: "The colorful arc after a storm.", sentence: "A double rainbow stretched over town." },
  { word: "raccoon", hint: "The masked critter that raids trash cans.", sentence: "A raccoon washed its food in the creek." },
  { word: "river", hint: "A wide stream that flows to the sea.", sentence: "We paddled down the lazy river." },
  { word: "salmon", hint: "The pink fish that swims upstream.", sentence: "Bears wait for salmon at the falls." },
  { word: "squirrel", hint: "The bushy-tailed acorn collector.", sentence: "A squirrel buried nuts in the yard." },
  { word: "thunder", hint: "The boom that follows the flash.", sentence: "Thunder rattled the windows." },
  { word: "tornado", hint: "A spinning funnel of wind.", sentence: "The tornado siren sent us to the basement." },
  { word: "turtle", hint: "It carries its house on its back.", sentence: "The turtle sunbathed on a log." },
  { word: "volcano", hint: "A mountain that can erupt with lava.", sentence: "The volcano rumbled all night." },
  { word: "waterfall", hint: "A river pouring off a cliff.", sentence: "Mist rose from the roaring waterfall." },
  { word: "whale", hint: "The biggest animal in the whole ocean.", sentence: "A whale surfaced near our boat." },
  { word: "zebra", hint: "The striped cousin of the horse.", sentence: "Every zebra has its own stripe pattern." },
];
