export type GradeBand = "k-1" | "2-3" | "4-5" | "6-plus";

export interface WordEntry {
  word: string;
  hint: string;
}

export interface GradeBandInfo {
  id: GradeBand;
  label: string;
  short: string;
  blurb: string;
}

export const GRADE_BANDS: GradeBandInfo[] = [
  {
    id: "k-1",
    label: "Grades K–1",
    short: "K–1",
    blurb: "Short, sound-it-out words like cat, sun, and hop.",
  },
  {
    id: "2-3",
    label: "Grades 2–3",
    short: "2–3",
    blurb: "Everyday words with tricky parts, like friend and because.",
  },
  {
    id: "4-5",
    label: "Grades 4–5",
    short: "4–5",
    blurb: "Longer words people often misspell, like separate and library.",
  },
  {
    id: "6-plus",
    label: "Grades 6+",
    short: "6+",
    blurb: "Challenge words like rhythm, committee, and mischievous.",
  },
];

export const WORD_LISTS: Record<GradeBand, WordEntry[]> = {
  "k-1": [
    { word: "cat", hint: "A furry pet that says meow." },
    { word: "dog", hint: "A pet that barks and wags its tail." },
    { word: "sun", hint: "The bright star that lights up the day." },
    { word: "hat", hint: "You wear it on your head." },
    { word: "run", hint: "To move very fast on your feet." },
    { word: "big", hint: "The opposite of small." },
    { word: "red", hint: "The color of a stop sign." },
    { word: "bed", hint: "Where you sleep at night." },
    { word: "cup", hint: "You drink juice from it." },
    { word: "six", hint: "The number after five." },
    { word: "box", hint: "A square container for keeping things." },
    { word: "pig", hint: "A farm animal that says oink." },
    { word: "hen", hint: "A mother chicken." },
    { word: "fox", hint: "A wild animal with a bushy tail." },
    { word: "bug", hint: "A tiny crawling insect." },
    { word: "mud", hint: "Wet dirt that squishes." },
    { word: "jam", hint: "Sweet fruit spread for toast." },
    { word: "nap", hint: "A short sleep in the daytime." },
    { word: "zip", hint: "What you do to close a jacket." },
    { word: "wet", hint: "How you feel after the rain." },
    { word: "top", hint: "The highest part of something." },
    { word: "sit", hint: "What you do on a chair." },
    { word: "ten", hint: "The number of fingers you have." },
    { word: "leg", hint: "You stand on two of these." },
    { word: "yes", hint: "The opposite of no." },
    { word: "win", hint: "To come in first place." },
    { word: "log", hint: "A big piece of a fallen tree." },
    { word: "hop", hint: "To jump like a bunny." },
    { word: "pan", hint: "You cook eggs in it." },
    { word: "map", hint: "A drawing that shows where places are." },
  ],
  "2-3": [
    { word: "because", hint: "The word that tells the reason why." },
    { word: "friend", hint: "Someone you like to play with." },
    { word: "school", hint: "The place where you learn." },
    { word: "little", hint: "Another word for small." },
    { word: "again", hint: "One more time." },
    { word: "always", hint: "Every single time, without fail." },
    { word: "animal", hint: "A dog, a lion, or a whale is one." },
    { word: "before", hint: "The opposite of after." },
    { word: "better", hint: "Good, gooder... no wait, this word!" },
    { word: "birthday", hint: "The day you were born, with cake!" },
    { word: "brother", hint: "A boy in your family with the same parents." },
    { word: "caught", hint: "What you did when the ball landed in your hands." },
    { word: "children", hint: "More than one child." },
    { word: "together", hint: "With each other, not alone." },
    { word: "morning", hint: "The time of day when you wake up." },
    { word: "mother", hint: "Another word for mom." },
    { word: "night", hint: "When the moon and stars come out." },
    { word: "people", hint: "More than one person." },
    { word: "please", hint: "The magic word when you ask for something." },
    { word: "pretty", hint: "Nice to look at, like a flower." },
    { word: "right", hint: "Correct, or the opposite of left." },
    { word: "said", hint: "The past of say." },
    { word: "there", hint: "Over in that place, not here." },
    { word: "thought", hint: "The past of think." },
    { word: "water", hint: "What you drink when you are thirsty." },
    { word: "where", hint: "The question word that asks about a place." },
    { word: "which", hint: "The question word for choosing one of two." },
    { word: "world", hint: "The whole planet Earth." },
    { word: "write", hint: "What you do with a pencil on paper." },
    { word: "every", hint: "Each one, with none left out." },
  ],
  "4-5": [
    { word: "beautiful", hint: "Very, very pretty." },
    { word: "believe", hint: "To think something is true." },
    { word: "business", hint: "A company that sells things or services." },
    { word: "calendar", hint: "It shows all the months and days of the year." },
    { word: "definitely", hint: "For sure, one hundred percent." },
    { word: "different", hint: "Not the same." },
    { word: "embarrass", hint: "To make someone's cheeks turn red." },
    { word: "enough", hint: "As much as you need, no more." },
    { word: "especially", hint: "More than all the others; particularly." },
    { word: "favorite", hint: "The one you like best of all." },
    { word: "February", hint: "The shortest month of the year." },
    { word: "finally", hint: "At last, after a long wait." },
    { word: "grammar", hint: "The rules for putting words in order." },
    { word: "happened", hint: "The past of happen." },
    { word: "important", hint: "Something that matters a lot." },
    { word: "island", hint: "Land with water all the way around it." },
    { word: "knowledge", hint: "Everything you know." },
    { word: "language", hint: "English, Spanish, and French are each one." },
    { word: "library", hint: "The building full of books to borrow." },
    { word: "minute", hint: "Sixty seconds." },
    { word: "necessary", hint: "Something you must have or do." },
    { word: "neighbor", hint: "The person who lives next door." },
    { word: "probably", hint: "Most likely, but not for sure." },
    { word: "receive", hint: "To get something that was given to you." },
    { word: "restaurant", hint: "A place where you pay to eat a meal." },
    { word: "separate", hint: "To split apart into pieces or groups." },
    { word: "straight", hint: "A line with no curves or bends." },
    { word: "surprise", hint: "Something you never saw coming." },
    { word: "tomorrow", hint: "The day after today." },
    { word: "weight", hint: "How heavy something is." },
  ],
  "6-plus": [
    { word: "accommodate", hint: "To make room for someone or something." },
    { word: "achievement", hint: "Something great that you worked hard to do." },
    { word: "acquire", hint: "To get or gain something." },
    { word: "apparent", hint: "Easy to see; obvious." },
    { word: "argument", hint: "A disagreement, or the reasons for your side." },
    { word: "committee", hint: "A group of people chosen to make decisions." },
    { word: "conscience", hint: "The little voice that tells you right from wrong." },
    { word: "curiosity", hint: "The itch to find out more." },
    { word: "desperate", hint: "Willing to try anything because you need it badly." },
    { word: "exaggerate", hint: "To make a story bigger than it really was." },
    { word: "existence", hint: "The state of being real." },
    { word: "foreign", hint: "From another country." },
    { word: "guarantee", hint: "A promise that something will happen." },
    { word: "immediately", hint: "Right now, without waiting." },
    { word: "independent", hint: "Able to do things on your own." },
    { word: "judgment", hint: "A decision or opinion after careful thought." },
    { word: "maintenance", hint: "The work of keeping something in good shape." },
    { word: "millennium", hint: "One thousand years." },
    { word: "mischievous", hint: "Playfully naughty, like a prankster." },
    { word: "occasionally", hint: "Once in a while, not often." },
    { word: "occurrence", hint: "Something that happens; an event." },
    { word: "privilege", hint: "A special right not everyone gets." },
    { word: "pronunciation", hint: "The way a word sounds when you say it." },
    { word: "questionnaire", hint: "A list of questions to fill out." },
    { word: "recommend", hint: "To tell someone they should try it." },
    { word: "rhythm", hint: "The beat you tap your foot to." },
    { word: "sincerely", hint: "The honest way to end a letter." },
    { word: "twelfth", hint: "The one that comes after eleventh." },
    { word: "vacuum", hint: "The machine that eats crumbs off the carpet." },
    { word: "parallel", hint: "Lines that run side by side and never touch." },
  ],
};
