export type GradeBand = "k-1" | "2-3" | "4-5" | "6-plus";

export interface WordEntry {
  word: string;
  hint: string;
  /** A short sentence using the word exactly once (any casing). */
  sentence: string;
}

export interface GradeBandInfo {
  id: GradeBand;
  label: string;
  short: string;
  blurb: string;
}

export const GRADE_BANDS: GradeBandInfo[] = [
  {
    id: "k-1",
    label: "Grades K–1",
    short: "K–1",
    blurb: "Short, sound-it-out words like cat, sun, and hop.",
  },
  {
    id: "2-3",
    label: "Grades 2–3",
    short: "2–3",
    blurb: "Everyday words with tricky parts, like friend and because.",
  },
  {
    id: "4-5",
    label: "Grades 4–5",
    short: "4–5",
    blurb: "Longer words people often misspell, like separate and library.",
  },
  {
    id: "6-plus",
    label: "Grades 6+",
    short: "6+",
    blurb: "Challenge words like rhythm, committee, and mischievous.",
  },
];

export const WORD_LISTS: Record<GradeBand, WordEntry[]> = {
  "k-1": [
    { word: "cat", hint: "A furry pet that says meow.", sentence: "My cat naps on the rug." },
    { word: "dog", hint: "A pet that barks and wags its tail.", sentence: "Our dog barks at the mail truck." },
    { word: "sun", hint: "The bright star that lights up the day.", sentence: "The sun is hot today." },
    { word: "hat", hint: "You wear it on your head.", sentence: "His hat blew off in the wind." },
    { word: "run", hint: "To move very fast on your feet.", sentence: "We run fast at recess." },
    { word: "big", hint: "The opposite of small.", sentence: "That truck is really big." },
    { word: "red", hint: "The color of a stop sign.", sentence: "She picked the red crayon." },
    { word: "bed", hint: "Where you sleep at night.", sentence: "I made my bed this morning." },
    { word: "cup", hint: "You drink juice from it.", sentence: "Pour the milk in my cup." },
    { word: "six", hint: "The number after five.", sentence: "There are six eggs left." },
    { word: "box", hint: "A square container for keeping things.", sentence: "Put the toys in the box." },
    { word: "pig", hint: "A farm animal that says oink.", sentence: "The pig rolled in the cool mud." },
    { word: "hen", hint: "A mother chicken.", sentence: "The hen laid one brown egg." },
    { word: "fox", hint: "A wild animal with a bushy tail.", sentence: "A fox ran into the woods." },
    { word: "bug", hint: "A tiny crawling insect.", sentence: "A tiny bug landed on my arm." },
    { word: "mud", hint: "Wet dirt that squishes.", sentence: "My boots are covered in mud." },
    { word: "jam", hint: "Sweet fruit spread for toast.", sentence: "She spread jam on her toast." },
    { word: "nap", hint: "A short sleep in the daytime.", sentence: "The baby takes a nap at noon." },
    { word: "zip", hint: "What you do to close a jacket.", sentence: "Please zip up your coat." },
    { word: "wet", hint: "How you feel after the rain.", sentence: "The grass is wet from the rain." },
    { word: "top", hint: "The highest part of something.", sentence: "He spun the top on the table." },
    { word: "sit", hint: "What you do on a chair.", sentence: "Please sit in your chair." },
    { word: "ten", hint: "The number of fingers you have.", sentence: "I counted ten little ducks." },
    { word: "leg", hint: "You stand on two of these.", sentence: "The chair has a wobbly leg." },
    { word: "yes", hint: "The opposite of no.", sentence: "She said yes right away." },
    { word: "win", hint: "To come in first place.", sentence: "Did our team win the game?" },
    { word: "log", hint: "A big piece of a fallen tree.", sentence: "A frog sat on the log." },
    { word: "hop", hint: "To jump like a bunny.", sentence: "Bunnies hop across the yard." },
    { word: "pan", hint: "You cook eggs in it.", sentence: "The eggs sizzled in the pan." },
    { word: "map", hint: "A drawing that shows where places are.", sentence: "We followed the map to the park." },
  ],
  "2-3": [
    { word: "because", hint: "The word that tells the reason why.", sentence: "We stayed inside because it rained." },
    { word: "friend", hint: "Someone you like to play with.", sentence: "My friend shared her snack with me." },
    { word: "school", hint: "The place where you learn.", sentence: "We walk to school together." },
    { word: "little", hint: "Another word for small.", sentence: "The little puppy chased its tail." },
    { word: "again", hint: "One more time.", sentence: "Let's read that story again." },
    { word: "always", hint: "Every single time, without fail.", sentence: "Dad always makes pancakes on Sunday." },
    { word: "animal", hint: "A dog, a lion, or a whale is one.", sentence: "What animal says moo?" },
    { word: "before", hint: "The opposite of after.", sentence: "Wash your hands before dinner." },
    { word: "better", hint: "Good, gooder... no wait, this word!", sentence: "I feel better after my nap." },
    { word: "birthday", hint: "The day you were born, with cake!", sentence: "Her birthday party is on Saturday." },
    { word: "brother", hint: "A boy in your family with the same parents.", sentence: "My brother lost his first tooth." },
    { word: "caught", hint: "What you did when the ball landed in your hands.", sentence: "She caught the ball with one hand." },
    { word: "children", hint: "More than one child.", sentence: "The children lined up for lunch." },
    { word: "together", hint: "With each other, not alone.", sentence: "We built the puzzle together." },
    { word: "morning", hint: "The time of day when you wake up.", sentence: "Every morning I brush my teeth." },
    { word: "mother", hint: "Another word for mom.", sentence: "His mother packed his lunch." },
    { word: "night", hint: "When the moon and stars come out.", sentence: "Stars come out at night." },
    { word: "people", hint: "More than one person.", sentence: "Many people were at the fair." },
    { word: "please", hint: "The magic word when you ask for something.", sentence: "May I please have more juice?" },
    { word: "pretty", hint: "Nice to look at, like a flower.", sentence: "That flower is so pretty." },
    { word: "right", hint: "Correct, or the opposite of left.", sentence: "Turn right at the corner." },
    { word: "said", hint: "The past of say.", sentence: "Mom said we can go swimming." },
    { word: "there", hint: "Over in that place, not here.", sentence: "Look over there by the fence!" },
    { word: "thought", hint: "The past of think.", sentence: "I thought the movie was funny." },
    { word: "water", hint: "What you drink when you are thirsty.", sentence: "Plants need water to grow." },
    { word: "where", hint: "The question word that asks about a place.", sentence: "Do you know where my shoes are?" },
    { word: "which", hint: "The question word for choosing one of two.", sentence: "Guess which hand holds the coin." },
    { word: "world", hint: "The whole planet Earth.", sentence: "A globe shows the whole world." },
    { word: "write", hint: "What you do with a pencil on paper.", sentence: "Please write your name at the top." },
    { word: "every", hint: "Each one, with none left out.", sentence: "She waters the garden every day." },
  ],
  "4-5": [
    { word: "beautiful", hint: "Very, very pretty.", sentence: "The sunset was beautiful tonight." },
    { word: "believe", hint: "To think something is true.", sentence: "I believe our team can win." },
    { word: "business", hint: "A company that sells things or services.", sentence: "Her mom runs a small business." },
    { word: "calendar", hint: "It shows all the months and days of the year.", sentence: "Mark the trip on the calendar." },
    { word: "definitely", hint: "For sure, one hundred percent.", sentence: "We will definitely come to the party." },
    { word: "different", hint: "Not the same.", sentence: "Each snowflake is different." },
    { word: "embarrass", hint: "To make someone's cheeks turn red.", sentence: "Please don't embarrass me at the recital." },
    { word: "enough", hint: "As much as you need, no more.", sentence: "We have enough pizza for everyone." },
    { word: "especially", hint: "More than all the others; particularly.", sentence: "I love fruit, especially mangoes." },
    { word: "favorite", hint: "The one you like best of all.", sentence: "Blue is my favorite color." },
    { word: "February", hint: "The shortest month of the year.", sentence: "Valentine's Day is in February." },
    { word: "finally", hint: "At last, after a long wait.", sentence: "The bus finally arrived." },
    { word: "grammar", hint: "The rules for putting words in order.", sentence: "Our teacher loves good grammar." },
    { word: "happened", hint: "The past of happen.", sentence: "Nobody knows what happened to the cookies." },
    { word: "important", hint: "Something that matters a lot.", sentence: "Drinking water is important." },
    { word: "island", hint: "Land with water all the way around it.", sentence: "The boat sailed to a small island." },
    { word: "knowledge", hint: "Everything you know.", sentence: "Books are full of knowledge." },
    { word: "language", hint: "English, Spanish, and French are each one.", sentence: "Spanish is her first language." },
    { word: "library", hint: "The building full of books to borrow.", sentence: "I returned my books to the library." },
    { word: "minute", hint: "Sixty seconds.", sentence: "Wait one minute, please." },
    { word: "necessary", hint: "Something you must have or do.", sentence: "A helmet is necessary for biking." },
    { word: "neighbor", hint: "The person who lives next door.", sentence: "Our neighbor waves every morning." },
    { word: "probably", hint: "Most likely, but not for sure.", sentence: "It will probably snow tonight." },
    { word: "receive", hint: "To get something that was given to you.", sentence: "Did you receive my letter?" },
    { word: "restaurant", hint: "A place where you pay to eat a meal.", sentence: "We ate noodles at a new restaurant." },
    { word: "separate", hint: "To split apart into pieces or groups.", sentence: "Please separate the red and blue blocks." },
    { word: "straight", hint: "A line with no curves or bends.", sentence: "Draw a straight line with a ruler." },
    { word: "surprise", hint: "Something you never saw coming.", sentence: "The party was a total surprise." },
    { word: "tomorrow", hint: "The day after today.", sentence: "Our field trip is tomorrow." },
    { word: "weight", hint: "How heavy something is.", sentence: "The vet checked the puppy's weight." },
  ],
  "6-plus": [
    { word: "accommodate", hint: "To make room for someone or something.", sentence: "The cabin can accommodate eight campers." },
    { word: "achievement", hint: "Something great that you worked hard to do.", sentence: "Winning the spelling bee was a huge achievement." },
    { word: "acquire", hint: "To get or gain something.", sentence: "Museums acquire new paintings every year." },
    { word: "apparent", hint: "Easy to see; obvious.", sentence: "Her talent was apparent right away." },
    { word: "argument", hint: "A disagreement, or the reasons for your side.", sentence: "They settled the argument with a coin flip." },
    { word: "committee", hint: "A group of people chosen to make decisions.", sentence: "The committee planned the school dance." },
    { word: "conscience", hint: "The little voice that tells you right from wrong.", sentence: "His conscience told him to return the wallet." },
    { word: "curiosity", hint: "The itch to find out more.", sentence: "Her curiosity led her to the science fair." },
    { word: "desperate", hint: "Willing to try anything because you need it badly.", sentence: "The wilted plant looked desperate for water." },
    { word: "exaggerate", hint: "To make a story bigger than it really was.", sentence: "Fishermen love to exaggerate their catches." },
    { word: "existence", hint: "The state of being real.", sentence: "Scientists debate the existence of life on Mars." },
    { word: "foreign", hint: "From another country.", sentence: "She collects coins from foreign countries." },
    { word: "guarantee", hint: "A promise that something will happen.", sentence: "They guarantee the backpack for life." },
    { word: "immediately", hint: "Right now, without waiting.", sentence: "Call me immediately after the game." },
    { word: "independent", hint: "Able to do things on your own.", sentence: "The kitten is small but independent." },
    { word: "judgment", hint: "A decision or opinion after careful thought.", sentence: "Use good judgment when crossing the street." },
    { word: "maintenance", hint: "The work of keeping something in good shape.", sentence: "The pool is closed for maintenance." },
    { word: "millennium", hint: "One thousand years.", sentence: "A millennium is ten centuries long." },
    { word: "mischievous", hint: "Playfully naughty, like a prankster.", sentence: "The mischievous puppy hid my sock." },
    { word: "occasionally", hint: "Once in a while, not often.", sentence: "We occasionally get donuts on Fridays." },
    { word: "occurrence", hint: "Something that happens; an event.", sentence: "A double rainbow is a rare occurrence." },
    { word: "privilege", hint: "A special right not everyone gets.", sentence: "Feeding the class hamster is a privilege." },
    { word: "pronunciation", hint: "The way a word sounds when you say it.", sentence: "The teacher modeled the correct pronunciation." },
    { word: "questionnaire", hint: "A list of questions to fill out.", sentence: "Please fill out the questionnaire honestly." },
    { word: "recommend", hint: "To tell someone they should try it.", sentence: "I recommend the blueberry muffins." },
    { word: "rhythm", hint: "The beat you tap your foot to.", sentence: "Clap to the rhythm of the song." },
    { word: "sincerely", hint: "The honest way to end a letter.", sentence: "She signed the letter sincerely yours." },
    { word: "twelfth", hint: "The one that comes after eleventh.", sentence: "My locker is the twelfth one on the left." },
    { word: "vacuum", hint: "The machine that eats crumbs off the carpet.", sentence: "Please vacuum the crumbs under the table." },
    { word: "parallel", hint: "Lines that run side by side and never touch.", sentence: "Train tracks run parallel to the river." },
  ],
};

/** Every word across every grade band, for filtering generated misspellings. */
export const ALL_WORDS: ReadonlySet<string> = new Set(
  Object.values(WORD_LISTS).flatMap((list) => list.map((e) => e.word.toLowerCase())),
);
