/**
 * Generates android/app/src/main/java/com/skdaddle/spellit/data/WordData.kt
 * from the web app's word lists, ending tasks, and safety lists, so the
 * Android app and the site share a single source of truth. Run with:
 * npm run generate:kotlin
 */
import { mkdirSync, writeFileSync } from "node:fs";

import { BUILT_IN_BANKS } from "../lib/banks";
import { BLOCKED_WORDS } from "../lib/blocked-words";
import { ENDING_TASKS } from "../lib/endings";
import { REAL_WORD_GUARD } from "../lib/real-word-guard";
import { GRADE_BANDS, WORD_LISTS, type GradeBand } from "../lib/words";

const KOTLIN_CASE: Record<GradeBand, string> = {
  "k-1": "K1",
  "2-3": "G23",
  "4-5": "G45",
  "6-plus": "G6_PLUS",
};

const esc = (s: string) =>
  s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$");

// Each band/bank gets its own private function so no single method body
// (or the object's initializer) grows past the JVM's 64K bytecode limit.
const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-kotlin-data.ts — do not edit.",
  "// Regenerate with `npm run generate:kotlin` after changing lib/words.ts,",
  "// lib/endings.ts, lib/blocked-words.ts, or the real-word guard.",
  "",
  "package com.skdaddle.spellit.data",
  "",
  "import com.skdaddle.spellit.model.EndingTask",
  "import com.skdaddle.spellit.model.GradeBand",
  "import com.skdaddle.spellit.model.WordBank",
  "import com.skdaddle.spellit.model.WordEntry",
  "",
  "object WordData {",
];

for (const band of GRADE_BANDS) {
  lines.push(`  private fun words${KOTLIN_CASE[band.id]}(): List<WordEntry> = listOf(`);
  for (const e of WORD_LISTS[band.id]) {
    lines.push(
      `    WordEntry("${esc(e.word)}", "${esc(e.hint)}", "${esc(e.sentence)}"),`,
    );
  }
  lines.push("  )");
}

lines.push("");
lines.push("  val words: Map<GradeBand, List<WordEntry>> by lazy {");
lines.push("    mapOf(");
for (const band of GRADE_BANDS) {
  lines.push(
    `      GradeBand.${KOTLIN_CASE[band.id]} to words${KOTLIN_CASE[band.id]}(),`,
  );
}
lines.push("    )");
lines.push("  }");

const bankFn = (id: string) => `bank${id.replace(/[^A-Za-z0-9]+/g, "_")}`;
for (const bank of BUILT_IN_BANKS) {
  lines.push("");
  lines.push(`  private fun ${bankFn(bank.id)}(): WordBank = WordBank(`);
  lines.push(
    `    id = "${esc(bank.id)}", name = "${esc(bank.name)}", blurb = "${esc(bank.blurb)}", builtIn = true,`,
  );
  lines.push("    entries = listOf(");
  for (const e of bank.entries) {
    const hint = e.hint ? `"${esc(e.hint)}"` : "null";
    const sentence = e.sentence ? `"${esc(e.sentence)}"` : "null";
    lines.push(`      WordEntry("${esc(e.word)}", ${hint}, ${sentence}),`);
  }
  lines.push("    ),");
  lines.push("  )");
}

lines.push("");
lines.push("  val builtInBanks: List<WordBank> by lazy {");
lines.push(
  `    listOf(${BUILT_IN_BANKS.map((b) => `${bankFn(b.id)}()`).join(", ")})`,
);
lines.push("  }");

for (const band of GRADE_BANDS) {
  lines.push("");
  lines.push(
    `  private fun endings${KOTLIN_CASE[band.id]}(): List<EndingTask> = listOf(`,
  );
  for (const t of ENDING_TASKS[band.id]) {
    const also = t.also
      ? `listOf(${t.also.map((a) => `"${esc(a)}"`).join(", ")})`
      : "emptyList()";
    lines.push(
      `    EndingTask("${esc(t.base)}", "${esc(t.suffix)}", "${esc(t.word)}", "${esc(t.hint)}", ${also}),`,
    );
  }
  lines.push("  )");
}

lines.push("");
lines.push("  val endings: Map<GradeBand, List<EndingTask>> by lazy {");
lines.push("    mapOf(");
for (const band of GRADE_BANDS) {
  lines.push(
    `      GradeBand.${KOTLIN_CASE[band.id]} to endings${KOTLIN_CASE[band.id]}(),`,
  );
}
lines.push("    )");
lines.push("  }");

lines.push("");
lines.push("  private fun guardWords(): List<String> = listOf(");
for (const w of REAL_WORD_GUARD) lines.push(`    "${esc(w)}",`);
lines.push("  )");
lines.push("");
lines.push("  val realWordGuard: Set<String> by lazy { guardWords().toSet() }");

lines.push("");
lines.push("  val blockedWords: List<String> = listOf(");
for (const w of BLOCKED_WORDS) lines.push(`    "${esc(w)}",`);
lines.push("  )");

lines.push("}");
lines.push("");

mkdirSync(
  new URL("../android/app/src/main/java/com/skdaddle/spellit/data", import.meta.url),
  { recursive: true },
);
writeFileSync(
  new URL(
    "../android/app/src/main/java/com/skdaddle/spellit/data/WordData.kt",
    import.meta.url,
  ),
  lines.join("\n"),
);
console.log(`Wrote WordData.kt (${lines.length} lines).`);
