/**
 * Regenerates lib/real-word-guard.ts: every misspelling candidate our
 * generator can produce for the current word lists that is actually a real
 * English word (per the system dictionary), plus an always-blocked list of
 * words that must never appear in a kids' game regardless of dictionaries.
 *
 * Run with: npm run generate:guard
 */
import { readFileSync, writeFileSync } from "node:fs";

import { misspellingCandidates } from "../lib/game-utils";
import { WORD_LISTS } from "../lib/words";

// Words that must never be shown to kids as a "fake spelling", whether or not
// a dictionary knows them.
const ALWAYS_BLOCKED = [
  "sex", "sexy", "ass", "arse", "hell", "damn", "crap", "piss", "tit", "tits",
  "cock", "dick", "cum", "fag", "fart", "poop", "pee", "butt", "nude", "porn",
];

const DICT_PATH = "/usr/share/dict/words";
const dictionary = new Set(
  readFileSync(DICT_PATH, "utf8")
    .split("\n")
    .map((w) => w.trim().toLowerCase())
    .filter(Boolean),
);

const collisions = new Set<string>(ALWAYS_BLOCKED);
let minPool = Infinity;
let minWord = "";

for (const list of Object.values(WORD_LISTS)) {
  for (const entry of list) {
    const candidates = misspellingCandidates(entry.word.toLowerCase());
    let clean = 0;
    for (const candidate of candidates) {
      if (dictionary.has(candidate) || ALWAYS_BLOCKED.includes(candidate)) {
        collisions.add(candidate);
      } else {
        clean++;
      }
    }
    if (clean < minPool) {
      minPool = clean;
      minWord = entry.word;
    }
    if (clean < 3) {
      console.error(
        `WARNING: "${entry.word}" has only ${clean} safe fakes — Spot the Word needs 3.`,
      );
      process.exitCode = 1;
    }
  }
}

const sorted = [...collisions].sort();
const body = sorted.map((w) => `  "${w}",`).join("\n");
writeFileSync(
  new URL("../lib/real-word-guard.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/generate-real-word-guard.ts — do not edit.\n` +
    `// Regenerate with \`npm run generate:guard\` after changing lib/words.ts\n` +
    `// or the misspelling rules in lib/game-utils.ts.\n` +
    `export const REAL_WORD_GUARD: readonly string[] = [\n${body}\n];\n`,
);

console.log(
  `Wrote ${sorted.length} guarded words. Smallest safe pool: "${minWord}" (${minPool} fakes).`,
);
