/**
 * Generates ios/SpellIt/Generated/WordData.swift from the web app's word
 * lists, ending tasks, and safety lists, so the iOS app and the site share a
 * single source of truth. Run with: npm run generate:swift
 */
import { mkdirSync, writeFileSync } from "node:fs";

import { BLOCKED_WORDS } from "../lib/blocked-words";
import { ENDING_TASKS } from "../lib/endings";
import { REAL_WORD_GUARD } from "../lib/real-word-guard";
import { GRADE_BANDS, WORD_LISTS, type GradeBand } from "../lib/words";

const SWIFT_CASE: Record<GradeBand, string> = {
  "k-1": "k1",
  "2-3": "g23",
  "4-5": "g45",
  "6-plus": "g6plus",
};

const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-swift-data.ts — do not edit.",
  "// Regenerate with `npm run generate:swift` after changing lib/words.ts,",
  "// lib/endings.ts, lib/blocked-words.ts, or the real-word guard.",
  "",
  "import Foundation",
  "",
  "enum WordData {",
];

lines.push("  static let words: [GradeBand: [WordEntry]] = [");
for (const band of GRADE_BANDS) {
  lines.push(`    .${SWIFT_CASE[band.id]}: [`);
  for (const e of WORD_LISTS[band.id]) {
    lines.push(
      `      WordEntry(word: "${esc(e.word)}", hint: "${esc(e.hint)}", sentence: "${esc(e.sentence)}"),`,
    );
  }
  lines.push("    ],");
}
lines.push("  ]");

lines.push("");
lines.push("  static let endings: [GradeBand: [EndingTask]] = [");
for (const band of GRADE_BANDS) {
  lines.push(`    .${SWIFT_CASE[band.id]}: [`);
  for (const t of ENDING_TASKS[band.id]) {
    const also = t.also
      ? `[${t.also.map((a) => `"${esc(a)}"`).join(", ")}]`
      : "[]";
    lines.push(
      `      EndingTask(base: "${esc(t.base)}", suffix: "${esc(t.suffix)}", word: "${esc(t.word)}", hint: "${esc(t.hint)}", also: ${also}),`,
    );
  }
  lines.push("    ],");
}
lines.push("  ]");

lines.push("");
lines.push("  static let realWordGuard: Set<String> = [");
for (const w of REAL_WORD_GUARD) lines.push(`    "${esc(w)}",`);
lines.push("  ]");

lines.push("");
lines.push("  static let blockedWords: [String] = [");
for (const w of BLOCKED_WORDS) lines.push(`    "${esc(w)}",`);
lines.push("  ]");

lines.push("}");
lines.push("");

mkdirSync(new URL("../ios/SpellIt/Generated", import.meta.url), {
  recursive: true,
});
writeFileSync(
  new URL("../ios/SpellIt/Generated/WordData.swift", import.meta.url),
  lines.join("\n"),
);
console.log(`Wrote WordData.swift (${lines.length} lines).`);
